---
- name: Install httpd package
  yum:
    #name: {{ pkg_web }}
    #state: latest
    name: httpd 
    state: latest

- name: start the service
  service:
    name: httpd 
    state: started
    enabled: true

- name: deliver html content
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: copy the config file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - sai-restart
   

