---
- name: play to install and configure http server
  hosts: servera
  user: devops
  become: true
  vars:
    package: httpd
  tasks:
    - name: install httpd
      yum:
        name: "{{ package }}"
        state: latest

  
