---
- name: play to install and configure http server
  hosts: web
  user: devops
  become: true
  #vars:
  #web_pkg: httpd
  #firewall_pkg: firewalld
  #web_service: httpd
  #firewall_service: firewalld
  #python_pkg: python-httplib2
  #rule: http
  #vars_files:
  #  - vars/vars.yml
  tasks:
    - name: install httpd
      yum:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest

    - name: start and enable httpd {{ web_pkg }} package
      service:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: start and enable the {{ firewall_service }} package
      service: 
        name: "{{ firewall_service }}"
        state: started
        enabled: true

    - name: create index file
      copy:
        content: "Example Web Content"
        dest: /var/www/html/index.html

    - name: open port for "{{ rule }}"
      firewalld:
        service: "{{ rule }}"
        state: enabled
        permanent: true
        immediate: true
...
